theme: jekyll-theme-minimal
title: Easy Inputs
description: A generic Forms generator for WordPress.
show_downloads: "true"
google_analytics: UA-1579586-2
github:
  zip_url: https://github.com/holisticnetworking/easy-inputs/archive/v1.0.1.zip
  tar_url: https://github.com/holisticnetworking/easy-inputs/archive/v1.0.1.tar.gz